version: '3.4'

services:
  webapi:
    image: AccountService
    build:
      context: .
      dockerfile: AccountService.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AccountServiceDB;User Id=SA;Password=123;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data: